[package]
name = "rost"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Write Rust in German"
license = "WTFPL"
repository = "https://github.com/michidk/rost"
readme = "../README.md"
keywords = ["german", "language", "macro", "rust"]
categories = ["development-tools::procedural-macro-helpers"]

[dependencies]

[lib]
proc-macro = true
